### PR TITLE
Protect delegated `check_*` methods

### PR DESCRIPTION
**Pull request by sanks64**
I noticed these weren't private when playing with [CrystalDoc.info](https://crystaldoc.info/github/phenopolis/pluto/v1.0.1/Pluto/Format/JPEG.html#check_jpeg%28%2Aargs%2C%2A%2Aoptions%29-instance-method).

This is indeed a breaking change, so the next release will have to be 2.0.0.

### CODE REVIEW

**Review by Vici37 — DISMISSED** [review]
Looks good to me! 

This is a rather unremarkable reason to update a major version, though. As an alternative, what if instead we marked the methods with:

```
# :nodoc:
@[Deprecated("The visibility of this method will be changing in the future, and it should not be used directly")]
delegate check_jpeg, to: self.class
```

And then during a more noteworthy major release change, go through and clean up any `@[Deprecated]` methods that were identified? That way we avoid the trap of doing a major version update for every technically-breaks-backwards-compatibility bug fix :sweat_smile: 

What do you think?

**Comment by sanks64** [comment]
Apparently it doesn't work in the suggested order, but does work reversed.

image

```
> crystal test.cr
Showing last frame. Use --error-trace for full trace.

In src/pluto/format/webp.cr:95:20

 95 | {% for subclass in Pluto::Image.subclasses %}
                         ^-----------
Error: undefined constant Pluto::Image
```

**Comment by sanks64** [comment]
Awesome suggestion, btw!

**Review by Vici37 — APPROVED** [review]
🚀

**Pull request merged**
